import { View, Text } from '@tarojs/components';
import Taro from '@tarojs/taro';

interface IconProps {
  name: string;
  size?: number;
  color?: string;
  className?: string;
  style?: any;
}

export const Icon = ({ name, size = 24, color = 'currentColor', className = '', style = {} }: IconProps) => {
  const iconMap: Record<string, string> = {
    'home': '🏠',
    'user': '👤',
    'add': '➕',
    'task': '📋',
    'search': '🔍',
    'location': '📍',
    'location-fill': '🎯',
    'back': '←',
    'arrow-right': '→',
    'arrow-left': '←',
    'arrow-up': '↑',
    'arrow-down': '↓',
    'close': '✕',
    'check': '✓',
    'check-circle': '✅',
    'warning': '⚠️',
    'error': '❌',
    'info': 'ℹ️',
    'success': '🎉',
    'loading': '⚡',
    'edit': '✏️',
    'delete': '🗑️',
    'send': '📤',
    'star': '⭐',
    'star-fill': '🌟',
    'heart': '❤️',
    'heart-fill': '❤️',
    'bell': '🔔',
    'message': '💬',
    'chat': '💭',
    'calendar': '📅',
    'clock': '⏰',
    'money': '💰',
    'coin': '🪙',
    'delivery': '📦',
    'help': '🙏',
    'tutoring': '📚',
    'school': '🏫',
    'book': '📖',
    'food': '🍜',
    'shop': '🏪',
    'car': '🚗',
    'bike': '🚲',
    'walk': '🚶',
    'bus': '🚌',
    'subway': '🚇',
    'map': '🗺️',
    'nav': '🧭',
    'camera': '📷',
    'image': '🖼️',
    'upload': '⬆️',
    'download': '⬇️',
    'share': '🔗',
    'link': '🔗',
    'setting': '⚙️',
    'more': '⋯',
    'more-vertical': '⋮',
    'filter': '🔍',
    'sort': '📊',
    'list': '📋',
    'grid': '▦',
    'refresh': '🔄',
    'sync': '🔄',
    'save': '💾',
    'copy': '📋',
    'clipboard': '📋',
    'lock': '🔒',
    'unlock': '🔓',
    'eye': '👁️',
    'eye-off': '🙈',
    'trending-up': '📈',
    'trending-down': '📉',
    'chart': '📊',
    'pie': '🥧',
    'target': '🎯',
    'goal': '🏆',
    'trophy': '🏆',
    'medal': '🏅',
    'crown': '👑',
    'fire': '🔥',
    'spark': '✨',
    'sparkles': '✨',
    'star2': '💫',
    'diamond': '💎',
    'gem': '💎',
    'gift': '🎁',
    'party': '🎉',
    'rocket': '🚀',
    'airplane': '✈️',
    'globe': '🌍',
    'earth': '🌎',
    'moon': '🌙',
    'sun': '☀️',
    'cloud': '☁️',
    'rain': '🌧️',
    'thunder': '⛈️',
    'snow': '❄️',
    'flash': '⚡',
    'zap': '⚡',
    'bolt': '⚡',
    'light': '💡',
    'bulb': '💡',
    'idea': '💡',
    'magic': '✨',
    'wand': '🪄',
    'sparkle': '✨',
    'firework': '🎆',
    'fireworks': '🎇',
    'sparkler': '🎇',
    'boom': '💥',
    'explode': '💥',
    'launch': '🚀',
    'send2': '🚀',
    'mail': '📧',
    'email': '✉️',
    'paperplane': '📧',
    'plane': '✈️',
    'helicopter': '🚁',
    'ship': '🚢',
    'boat': '⛵',
    'anchor': '⚓',
    'wave': '🌊',
    'water': '💧',
    'drop': '💧',
    'fire2': '🔥',
    'flame': '🔥',
    'flames': '🔥',
    'hot': '🔥',
    'cold': '❄️',
    'freeze': '❄️',
    'ice': '🧊',
    'cool': '😎',
    'smile': '😊',
    'happy': '😄',
    'joy': '😂',
    'laugh': '😆',
    'wink': '😉',
    'heart2': '💖',
    'love': '💝',
    'crush': '💘',
    'kiss': '💋',
    'hug': '🤗',
    'high-five': '🙌',
    'clap': '👏',
    'thumb-up': '👍',
    'thumb-down': '👎',
    'ok': '👌',
    'yes': '✅',
    'no': '❌',
    'maybe': '🤔',
    'think': '🤔',
    'question': '❓',
    'exclamation': '❗',
    'exclamation2': '❕',
    'question2': '❔',
    'curly': '〰️',
    'dash': '—',
    'bullet': '•',
    'dot': '•',
    'circle': '○',
    'circle-fill': '●',
    'square': '□',
    'square-fill': '■',
    'triangle': '△',
    'triangle-fill': '▲',
    'diamond2': '◇',
    'diamond2-fill': '◆',
    'star3': '☆',
    'star3-fill': '★',
    'heart3': '♡',
    'heart3-fill': '♥',
    'spade': '♠',
    'club': '♣',
    'diamond3': '♦',
    'heart4': '♡',
    'heart4-fill': '♥',
    'spade2': '♠',
    'club2': '♣',
    'diamond4': '♦',
    'heart5': '♡',
    'heart5-fill': '♥',
    'spade3': '♠',
    'club3': '♣',
    'diamond5': '♦',
    'heart6': '♡',
    'heart6-fill': '♥',
    'spade4': '♠',
    'club4': '♣',
    'diamond6': '♦',
    'heart7': '♡',
    'heart7-fill': '♥',
    'spade5': '♠',
    'club5': '♣',
    'diamond7': '♦',
    'heart8': '♡',
    'heart8-fill': '♥',
    'spade6': '♠',
    'club6': '♣',
    'diamond8': '♦',
    'heart9': '♡',
    'heart9-fill': '♥',
    'spade7': '♠',
    'club7': '♣',
    'diamond9': '♦',
    'heart10': '♡',
    'heart10-fill': '♥',
    'spade8': '♠',
    'club8': '♣',
    'diamond10': '♦',
    'heart11': '♡',
    'heart11-fill': '♥',
    'spade9': '♠',
    'club9': '♣',
    'diamond11': '♦',
    'heart12': '♡',
    'heart12-fill': '♥',
    'spade10': '♠',
    'club10': '♣',
    'diamond12': '♦',
    'heart13': '♡',
    'heart13-fill': '♥',
    'spade11': '♠',
    'club11': '♣',
    'diamond13': '♦',
    'heart14': '♡',
    'heart14-fill': '♥',
    'spade12': '♠',
    'club12': '♣',
    'diamond14': '♦',
    'heart15': '♡',
    'heart15-fill': '♥',
    'spade13': '♠',
    'club13': '♣',
    'diamond15': '♦',
    'heart16': '♡',
    'heart16-fill': '♥',
    'spade14': '♠',
    'club14': '♣',
    'diamond16': '♦',
    'heart17': '♡',
    'heart17-fill': '♥',
    'spade15': '♠',
    'club15': '♣',
    'diamond17': '♦',
    'heart18': '♡',
    'heart18-fill': '♥',
    'spade16': '♠',
    'club16': '♣',
    'diamond18': '♦',
    'heart19': '♡',
    'heart19-fill': '♥',
    'spade17': '♠',
    'club17': '♣',
    'diamond19': '♦',
    'heart20': '♡',
    'heart20-fill': '♥',
    'spade18': '♠',
    'club18': '♣',
    'diamond20': '♦',
    'heart21': '♡',
    'heart21-fill': '♥',
    'spade19': '♠',
    'club19': '♣',
    'diamond21': '♦',
    'heart22': '♡',
    'heart22-fill': '♥',
    'spade20': '♠',
    'club20': '♣',
    'diamond22': '♦',
    'heart23': '♡',
    'heart23-fill': '♥',
    'spade21': '♠',
    'club21': '♣',
    'diamond23': '♦',
    'heart24': '♡',
    'heart24-fill': '♥',
    'spade22': '♠',
    'club22': '♣',
    'diamond24': '♦',
    'heart25': '♡',
    'heart25-fill': '♥',
    'spade23': '♠',
    'club23': '♣',
    'diamond25': '♦',
    'heart26': '♡',
    'heart26-fill': '♥',
    'spade24': '♠',
    'club24': '♣',
    'diamond26': '♦',
    'heart27': '♡',
    'heart27-fill': '♥',
    'spade25': '♠',
    'club25': '♣',
    'diamond27': '♦',
    'heart28': '♡',
    'heart28-fill': '♥',
    'spade26': '♠',
    'club26': '♣',
    'diamond28': '♦',
    'heart29': '♡',
    'heart29-fill': '♥',
    'spade27': '♠',
    'club27': '♣',
    'diamond29': '♦',
    'heart30': '♡',
    'heart30-fill': '♥',
    'spade28': '♠',
    'club28': '♣',
    'diamond30': '♦',
    'heart31': '♡',
    'heart31-fill': '♥',
    'spade29': '♠',
    'club29': '♣',
    'diamond31': '♦',
    'heart32': '♡',
    'heart32-fill': '♥',
    'spade30': '♠',
    'club30': '♣',
    'diamond32': '♦',
    'heart33': '♡',
    'heart33-fill': '♥',
    'spade31': '♠',
    'club31': '♣',
    'diamond33': '♦',
    'heart34': '♡',
    'heart34-fill': '♥',
    'spade32': '♠',
    'club32': '♣',
    'diamond34': '♦',
    'heart35': '♡',
    'heart35-fill': '♥',
    'spade33': '♠',
    'club33': '♣',
    'diamond35': '♦',
    'heart36': '♡',
    'heart36-fill': '♥',
    'spade34': '♠',
    'club34': '♣',
    'diamond36': '♦',
    'heart37': '♡',
    'heart37-fill': '♥',
    'spade35': '♠',
    'club35': '♣',
    'diamond37': '♦',
    'heart38': '♡',
    'heart38-fill': '♥',
    'spade36': '♠',
    'club36': '♣',
    'diamond38': '♦',
    'heart39': '♡',
    'heart39-fill': '♥',
    'spade37': '♠',
    'club37': '♣',
    'diamond39': '♦',
    'heart40': '♡',
    'heart40-fill': '♥',
    'spade38': '♠',
    'club38': '♣',
    'diamond40': '♦',
    'heart41': '♡',
    'heart41-fill': '♥',
    'spade39': '♠',
    'club39': '♣',
    'diamond41': '♦',
    'heart42': '♡',
    'heart42-fill': '♥',
    'spade40': '♠',
    'club40': '♣',
    'diamond42': '♦',
    'heart43': '♡',
    'heart43-fill': '♥',
    'spade41': '♠',
    'club41': '♣',
    'diamond43': '♦',
    'heart44': '♡',
    'heart44-fill': '♥',
    'spade42': '♠',
    'club42': '♣',
    'diamond44': '♦',
    'heart45': '♡',
    'heart45-fill': '♥',
    'spade43': '♠',
    'club43': '♣',
    'diamond45': '♦',
    'heart46': '♡',
    'heart46-fill': '♥',
    'spade44': '♠',
    'club44': '♣',
    'diamond46': '♦',
    'heart47': '♡',
    'heart47-fill': '♥',
    'spade45': '♠',
    'club45': '♣',
    'diamond47': '♦',
    'heart48': '♡',
    'heart48-fill': '♥',
    'spade46': '♠',
    'club46': '♣',
    'diamond48': '♦',
    'heart49': '♡',
    'heart49-fill': '♥',
    'spade47': '♠',
    'club47': '♣',
    'diamond49': '♦',
    'heart50': '♡',
    'heart50-fill': '♥',
    'spade48': '♠',
    'club48': '♣',
    'diamond50': '♦',
    'heart51': '♡',
    'heart51-fill': '♥',
    'spade49': '♠',
    'club49': '♣',
    'diamond51': '♦',
    'heart52': '♡',
    'heart52-fill': '♥',
    'spade50': '♠',
    'club50': '♣',
    'diamond52': '♦',
  };

  const icon = iconMap[name] || '❓';

  return (
    <Text
      className={`icon-component ${className}`}
      style={{
        fontSize: `${size}px`,
        color: color,
        lineHeight: 1,
        display: 'inline-block',
        verticalAlign: 'middle',
        ...style
      }}
    >
      {icon}
    </Text>
  );
};

export default Icon;